### ISSUE TITLE
Upgraded to v11 and various odd problems

### ISSUE THREAD

**Issue by peterjohnhartman** [janten/dpt-rp1-py#110]
I'm in the process of trying to sort this out still, but two repeated problems I've noticed when I do: dptrp1 sync ~/Document Document

This happens even if I delete .sync and start over.

(1) It will detect the folders and subfolders as 'new' and attempt to UPLOAD them.  (I have 57 folders and sub-folders.)  It does this every single time.

(2) In one of my folders, it seems to pick 1 or 2 random individual files that it thinks are new and attempts to UPLOD them as well.  I haven't seen a rhyme or reason on this one just yet.

Let me know what I can provide to help debug this.  It is the latest git version of dpt-rp1-py.

Edit:
(2) I think was a fluke with a particular directory.  Once I deleted it, that stopped happening.

(1) I think *might* be because the folders themselves have a different timestamp on the local machine than on the DPT and so it tries to upload them each sync as if they are newer.  (But it appears it cannot update the folder timestamps on the DPT and so it fails.)

**Comment by peterjohnhartman** [comment]
A small update once more.
Re (2): If I change the script to do dptrp1 sync ~/Document/Subfolder Document/Subfolder it no longer attempts to UPLOAD the Document folder.  I think there's some sort of glitch with trying to sync at the ground floor with Document.  Even when I deleted everything on the DPT and locally, running dptrp1 sync ~/Document Document still attempted to UPLOAD the Document folder each time.

Re (1): Now that I've cleared the DPT, I can no longer reproduce this :-)

**Comment by peterjohnhartman** [comment]
Another small update after more testing.  I've narrowed the oddness down a bit, and I suspect things go off the rails when the number of files is over a certain threshold.  I have one directory with around 1212 pdf files in it (2.5G).  (Size is not the issue since I'm nowhere near the 9-11G capacity.)  When I attempt to sync this directory, things go off the rails in a really odd way and it isn't exactly consistent, but one effect is that if I do:

dptrp1 list-folders 

after uploading the directory, most of my folders just disappear.  It also attempts to download and upload and delete random things.

I haven't narrowed down two things: (1) if it is actually the NUMBER of files or if one of the files is kind of odd and screws up something, e.g., in the naming; or (2) if it is the NUMBER of files, what the precise number might be.

Hope that is clear enough.  Any help on debugging this would be much appreciated and if I can provide more clear information, I'd be happy to.

**Comment by janten** [comment]
I do not have a folder with that many files to test, but maybe the device only sends a limited amount of files or data per request. Could you try to sync the folder, then do a `dptrp1 list-folders | wc` and copy the results here? If you can try multiple times, that would be even more helpful.

**Comment by janten** [comment]
PS: Maybe try `list-documents`, too.

**Comment by peterjohnhartman** [comment]
Ok, I cleared the DPT (factory reset) and started from scratch.  Here is list-folders before I uploaded the ~1200 files.  Here is list-documents before.  (Both attached).

A few things:
(1) The directory 'phil' has the ~1200 documents.  I initially did this:

cp -a phil dptrp1/phil
dptrp1 sync ~/dptrp1 Document

It did *not* try to sync the 'phil' directory.

So next I just did:
rm -rf dptrp1/phil
mkdir dptrp1/phil
cp -a phil/A* dptrp1/phil/ (Only about 15 pdf files)
dptrp1 sync ~/dptrp1 Document

It did try (and successfully) sync'd the 'phil' directory.

That's when I took the list-folders and list-documents txt file snapshots.  Everything works 'fine' moving / editing single files, etc.  But then...

(2) I then copied the remaining ~1200 pdf files into dptrp1/phil and re-ran dptrp1 sync ~/dptrp1 Document.  It did commence to UPLOAD ~1209 (like I would expect).  But then...

(a) list-documents lists the right number of documents (see attached)
(b) list-folders misses out on a number of folders (see attached)!!!

And the next sync I do attempts to re-upload files already on the DPT (see attachment).

So that's where I'm stuck.  
[list-folders-before.txt](https://github.com/janten/dpt-rp1-py/files/4652270/list-folders-before.txt)
[list-documents-before.txt](https://github.com/janten/dpt-rp1-py/files/4652271/list-documents-before.txt)
[list-folders-after.txt](https://github.com/janten/dpt-rp1-py/files/4652273/list-folders-after.txt)
[list-documents-after.txt](https://github.com/janten/dpt-rp1-py/files/4652274/list-documents-after.txt)
[sync-after.txt](https://github.com/janten/dpt-rp1-py/files/4652276/sync-after.txt)






This is where it goes off the rail.

**Comment by hakon-j-d-johnsen** [comment]
From your description, I suspect that the issue lies in the `/documents2?entry_type=all` endpoint returning truncated data when there are very many files. This leads to incomplete data being returned from `dptrp1.list_all()`, which is used both by `list-folders` and by `sync`.

If this is the case, a quick fix for the synchronization would be to simply revert commit 2715c57fae5373776090a341d7d0222baa103439 where I made `dptrp1.traverse_folder()` use `dptrp1.list_all()`. A corresponding fix for `list-folder` would be to revert 72fcee9fbcd27ee215851346b950daf8247aa386. However, the reason for both of these commits was the significant performance improvement by reducing the number of requests to the device. Perhaps we should investigate whether `/documents2?entry_type=all` gives any indication that it is truncating data. (Perhaps it is even just paginating the data?)

**Comment by hakon-j-d-johnsen** [comment]
I currently have 939 PDFs on my device, but have not seen the same issue.

To debug further and see if the problem is with the `/documents2?entry_type=all` endpoint, could you look at the output of the following: 
```python
from dptrp1.dptrp1 import DigitalPaper, find_auth_files
addr = None
id = None

dp = DigitalPaper(
    addr=addr, id=id)
file_client_id, file_key = find_auth_files()

with open(file_client_id) as fh:
    client_id = fh.readline().strip()
with open(file_key, "rb") as fh:
    key = fh.read()

dp.authenticate(client_id, key)

response = dp._get_endpoint("/documents2?entry_type=all")
print("Contents:\n", response.content)
```
 (Fill in addr and id depending on how you typically connect to your device, and run it as a Python script or in a Python shell)

If it works correctly, it should print a json structure listing all the files and folders on your device, but from your description it sounds like it might be returning only a subset of your files. Maybe it also returns some pagination information or anything else that can be used to get the remaining files.

**Comment by hakon-j-d-johnsen** [comment]
Interestingly I've not been able to repliate the issue even after adding more files. Now, with 1273 PDFs, everything is still working fine on my end. Maybe the issue could be with a specific file (or file name) among your PDFs, not with the number of files?

**Comment by peterjohnhartman** [comment]
Here's the output from the above python script.  Interesting to learn that you didn't have the problem with your files.  This certainly suggests it might be a filename that it throwing it off for a loop.  I might try to test it again just duplicating a safe 'a.pdf' 4000 times or something and see if it still happens. 
[test-output.txt](https://github.com/janten/dpt-rp1-py/files/4665239/test-output.txt)

**Comment by peterjohnhartman** [comment]
Ok, I -think- I have it narrowed down to Document #.  Up to 1290 PDF files and sync works fine.  As soon as I add the 1291st, it goes off the rails!

**Comment by hakon-j-d-johnsen** [comment]
Yeah, I think you are right. In other words I came just barely short of replicating it yesterday, should have just added a few more PDFs.

From your test-output, the `/documents2?entry_type=all` endpoint returns a `count` of 1388 items, but the `entry_list` contains only 1300 items. The missing entries confuses the sync logic, causing the issues. The reason that you see the issue already at 1291 PDFs is that it is also counting the folders, not just the files.

A possible way to resolve this would be to double-check that `count` is equal to the length of `entry_list`, and if it is not, go back to using the slower recursive directory traversal. I can try to find time to prepare a pull request early next week (unless anyone else wants to look at it in the mean time).

@janten, if you are still familiar with the structure of the official DPTRP1 app, maybe you could also have a look to see if you see any traces of pagination in the API, so that we could get to the entries beyond the first 1300 without falling back to recursively traversing the directories?

**Comment by hakon-j-d-johnsen** [comment]
I have prepared a pull request now to solve this issue, sorry for taking some time.

I was also able to reproduce the issue on my system, and confirm that the pull request solves the problem.

**Comment by janten** [comment]
Merged. Thanks!
