### ISSUE TITLE
sync throws error 'count' on refreshing file information

### ISSUE THREAD

**Issue by paulibaadsager** [janten/dpt-rp1-py#129]
Syncing a folder with Fujitsu Quaderno A4 Gen. 2 used to work (via wifi), now dptrp1 won't sync files and throws an error.
Running 
`dptrp1 --addr 10.91.1.191 sync /home/pauli/quaderno`
gives `Refreshing file information... An error occured: 'count'` and no files are transfered.

After initializing the Quaderno (and deleting all files on it), and running the `dptrp1 sync` command again, it uploaded all files to the Quaderno, but then ends with
```
Synchronizing: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1069/1069 [27:28<00:00,  1.54s/files]
Refreshing file information... An error occured: 'count'
For help, call: /home/pauli/containers/dpt/bin/dptrp1 help sync
```
And we are back to scratch, and the device will not sync any files.

**Comment by hakon-j-d-johnsen** [comment]
It seems like the `count` property from the `/documents2?entry_type=all` is missing after uploading all your files, causing the `traverse_folder` function to fail. Since it used to work for you, I would expect that it is either something about the number of files, or something about one specific file that trips up the device. You could perhaps try resetting the device and uploading only a fraction of the files, to try to identify the file (or or number of files) that cause the problem.

Another quick hack that you could try to see if it fixes your problem is to modify line 394 in your dptrp1.py;
https://github.com/janten/dpt-rp1-py/blob/cc62c44f37679550c08c351b320ea971ca52db1f/dptrp1/dptrp1.py#L394
Change `["count"]` to `.get("count")`. In this way, the code won't throw an exception when the `count` attribute is missing, but instead it will try another mehtod that might still work on your device.

Other than this issue, it is interesting to hear that you've had success with Quaderno A4 Gen 2. You did not run into #124?

**Comment by paulibaadsager** [comment]
Thanks for your reply. It seems be a error caused by the number of files.

I initialized the Quaderno and uploaded my files in small fractions. Somewhere around a total of 1000 files the 'count'-error occurred.
Then I initialized the Quaderno again and uploaded all files except the last small (fail-coursing) fraction of files. Then instead of uploading more files, I copied 49-files in the synchronized folder (aka files that didn't cause error). 
When syncing, the 'count'-error occurred again. 
I recorded the terminal here: [https://asciinema.org/a/u5C1dXVLof0ZhiNMYbhegk49T?speed=3](https://asciinema.org/a/u5C1dXVLof0ZhiNMYbhegk49T?speed=3)

Then I deleted all files on the Quaderno, and changed the code in dptrp1.py as you suggested:
```
#if entry_data["count"] != len(entry_data["entry_list"]):
if entry_data.get("count") != len(entry_data["entry_list"]):

```
Then deleted the fail-causing test-files in sync-folder, and ran synchronize. Result: Okay
Then copied files in sync-folder, and ran synchronize again. Result: The 'count'-error occurred again. 

So not even the code change to `.get("count")` solved my problem.

About #124 I had no issues at all registering. It just worked excellent.

**Comment by hakon-j-d-johnsen** [comment]
Interesting, so I guess the Quaderno does something different than the original DPT-RP1 when the file number becomes larger.

I'm surprised that you get the same error after changing to `.get("count")`.  This is the only place I can see where I would expect your error to be generated. Unfortunately, the exception handling in `cli/dptrp1.py` throws away a lot of the info, giving you such a short error message. As a hack to get more details in the error message, you could replace `sys.exit(0)` with `raise e` in `cli/dptrp1.py` on line 376:

https://github.com/janten/dpt-rp1-py/blob/01383a28a4ea3d888d37e3e1218db082c08ba44b/dptrp1/cli/dptrp1.py#L373-L376

It might also be interesting to see what happens to the output from the quaderno when the number of files is too large. As a hack to debug it, you could add `print(entry_data)` on a line before that `entry_data.get("count")` change. (This will probably/hopefully give a relatively large output with all your filenames. So if you don't want to share all of it, you could also see what `print(entry_data.keys())` gives)

**Comment by paulibaadsager** [comment]
Sorry, I made a mistake (I made changes in the code cloned via git, but ran code installed via pip).

When I change to `.get("count")` the correct place, the error message does change. After also replacing `sys.exit(1)` with `raise e` in `cli/dptrp1.py`, the error looks like this

```
Looking for changes on device... {'error_code': '40800', 'message': 'The request was timeout.'}
An error occured: 'entry_list'
For help, call: /home/pauli/containers/dpt/bin/dptrp1 help sync
Traceback (most recent call last):
  File "/home/pauli/containers/dpt/bin/dptrp1", line 32, in <module>
    sys.exit(load_entry_point('dpt-rp1-py==0.1.13', 'console_scripts', 'dptrp1')())
  File "/home/pauli/containers/dpt/lib/python3.9/site-packages/dpt_rp1_py-0.1.13-py3.9.egg/dptrp1/cli/dptrp1.py", line 376, in main
    raise e
  File "/home/pauli/containers/dpt/lib/python3.9/site-packages/dpt_rp1_py-0.1.13-py3.9.egg/dptrp1/cli/dptrp1.py", line 371, in main
    commands[args.command](dp, *args.command_args)
  File "/home/pauli/containers/dpt/lib/python3.9/site-packages/dpt_rp1_py-0.1.13-py3.9.egg/dptrp1/cli/dptrp1.py", line 138, in do_sync
    d.sync(local_path, remote_path)
  File "/home/pauli/containers/dpt/lib/python3.9/site-packages/dpt_rp1_py-0.1.13-py3.9.egg/dptrp1/dptrp1.py", line 572, in sync
    remote_info = self.traverse_folder(
  File "/home/pauli/containers/dpt/lib/python3.9/site-packages/dpt_rp1_py-0.1.13-py3.9.egg/dptrp1/dptrp1.py", line 396, in traverse_folder
    if entry_data.get("count") != len(entry_data["entry_list"]):
KeyError: 'entry_list'
```
The added line `print(entry_data)` did give a list of all files, but only as long as the sync worked (otherwise the output is the error above).

Even when synchronizing doesn't work the command `dptrp1 list-documents` gives a list of all documents, whereas the command `dptrp1 list-folders` gives the error `An error occured: 'entry_list'`

**Comment by hakon-j-d-johnsen** [comment]
Thank you very much for the details! It seems like this issue is very similar to the old #110 in that the `/documents2?entry_type=all` endpoint doesn't work correctly with a large number of documents. While the DPT RP1 only returned a subset of the documents, the Quaderno A4 Gen 2 seems to detect the issue and return a timeout error.

The easiest way to solve this is probably to re-use the existing logic used to solve #110, but not assume the presence of `count` and `entry_list` . I believe a small additional change on line line 394 in dptrp1.py should be sufficient:
Change
`if entry_data["count"] != len(entry_data["entry_list"]):`
into:
`if entry_data.get("count") != len(entry_data.get("entry_list", [])):`

This change will (hopefully) solve the synchronization issue, but not `dptrp1 list-folders` issue. That one can probably also be fixed using a recursive directory traversal, but I am not sure what the cleanest way to do so would be. In any case, the highest priority is probably to get the sync to work again.

Perhaps you can verify that such a modification works, @paulibaadsager? If so, I can prepare a pull request (or if you want, you can also submit it as a pull request yourself after testing it).

**Comment by paulibaadsager** [comment]
Thank you! I can confirm that your solution works (both with a few hundred files and with more than 1100 files on the Quaderno).

**Comment by janten** [comment]
I have merged your PR (thanks!) and will close this issue now. Feel free to re-open if the problem persists.
