### ISSUE TITLE
A new feature? -- Plugin of Zotero

### ISSUE THREAD

**Issue by SwaySZ** [janten/dpt-rp1-py#40]
Hi there,

Sorry for claiming a fake issue here. Is it possible to write a plugin to Zotero? Thanks!

Best,
Sway

**Comment by janten** [comment]
I am not familiar with Zotero's plugin system, but you may be able to write a plugin for Zotero that uses dpt-rp1-py internally. You may also be able to use the [Zotero API](https://www.zotero.org/support/dev/web_api/v3/start) in conjunction with this python package to write a simple sync script between those.

I am closing this issue since such a plugin (or script) would be out of scope for this repository, but feel free to open a new issue or contact me directly with any questions if you build such a plugin.
