### ISSUE TITLE
Path.home() undefined

### ISSUE THREAD

**Issue by peterjohnhartman** [janten/dpt-rp1-py#90]
Hi thanks for the great program! --- been running it a month now.  One of the newer commits broke something on my linux machine:

On line 28 (in get_default_auth_files()) the line:

**config_path = os.path.join(Path.home(), ".dpapp")**

fails on my Linux (archlinux, python3) system.  This appears to be part of one of the recent git commits.  Change the line to:

**config_path = os.path.join("/home/peterjh/.dpapp")** 

makes it work --- although clearly there's likely a much better solution.  Will dig a bit deeper happy to test a patch locally

**Comment by hakon-j-d-johnsen** [comment]
Hi Peter,

I recently submitted a pull request with some changes to get_default_auth_files() that might be responsible for your issue. Could you provide the full error message to make it easier to identify the problem?

The specific line you refer to has stayed unchanged for several months. Are you sure the this is what causes the problem? You could try to run the following command, which does the same as the line you refer to:

`python3 -c "from pathlib import Path; import os; print(repr(os.path.join(Path.home(),'.dpapp')))"`

I would expect the above command to return `'/home/peterjh/.dpapp'` in your case. Let me know if it returns something else.

Best,
Håkon

**Comment by hakon-j-d-johnsen** [comment]
>  Could you provide the full error message to make it easier to identify the problem?

Oh, sorry. Apparently I did not read the subject line of the issue, where you actually provided the error message.

It seems like you are using a Python version older than Python 3.5, before [Path.home()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.home) was introduced.

You can fix the issue either by upgrading Python or by replacing `Path.home()` with `os.path.expanduser('~')`. 

@janten, how important do you think it is to support older Python versions? Let me know if you want a pull request with this specific change. However, since there are currently no unit tests, it would be difficult to guarantee complete compatibility with older python versions.

**Comment by peterjohnhartman** [comment]
Yep, that's the error, but oddly python --version tells me I am using 3.7.4.  The proposed patch (os.path.expanduser) fixed the issue, however. 

Will fiddle to see why the docs say it is in > 3.5 but for some reason my box reports 3.7.4.

**Comment by janten** [comment]
> @janten, how important do you think it is to support older Python versions? Let me know if you want a pull request with this specific change. However, since there are currently no unit tests, it would be difficult to guarantee complete compatibility with older python versions.

We never committed ourselves to any specific version of Python for this repository, so older versions are always supported on a best-effort basis only. If it's an easy fix, I'd gladly merge a PR.

**Comment by hakon-j-d-johnsen** [comment]
> Yep, that's the error, but oddly python --version tells me I am using 3.7.4.

Hmm, strange. Do you have different versions of python on your system? Perhaps dptrp1 was installed in such a way that it uses a different Python installation from the one you get when you run `python --version`?

If you want to get to the bottom of this, you could try the following commands:

**Which python executable is used by dpt-rp1:**
```bash
head -n1 `which dptrp1`
```

**Which python executable is used when running `python`:**
```bash
which python
```

**Whether Path.home() is available when running `python` directly:**
```bash
python -c "from pathlib import Path; print(Path.home())"
```

In any case, I have submitted a pull request that replaces `Path.home()` with `os.path.expanduser('~')`, in order to fix the problem for you and for people running Python < 3.5.
