### ISSUE TITLE
A lot of docs are synced again after paired with another computer

### ISSUE THREAD

**Issue by liboyue** [janten/dpt-rp1-py#96]
Thanks for this fantastic tool! I have a question about syncing using two computers.

After I pair my DPT-RP1 with a new computer, I need to sync a Dropbox folder to my digital paper, both this tool (and the official digital paper app) will upload a lot of documents again. I use Dropbox to sync that  folder between different computers, and on both computers the paths are exactly the same.

I was wondering what is the possible reason that exactly the same document would be treated differently? Thanks!

**Comment by hakon-j-d-johnsen** [comment]
Two possible causes come to mind: 
* Either: Dropbox does not transfer the hidden `.sync`, which used to store metadata about synchronization.
* Or: Dropbox changes the modification time for the transferred documents, so they appear to have been changed.

If the cause is a missing `.sync` file, this will be handled better once #88 is merged.

**Comment by liboyue** [comment]
I am not sure what caused this problem, but now it is fixed. Sorry I forgot to close this issue.
